//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputationServer.WebService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComputationServer.WebService.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request failed, bad parameters.
        /// </summary>
        internal static string LogBadParams {
            get {
                return ResourceManager.GetString("LogBadParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request failed, exception occured.
        /// </summary>
        internal static string LogException {
            get {
                return ResourceManager.GetString("LogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request failed, just because.
        /// </summary>
        internal static string LogRequestFailed {
            get {
                return ResourceManager.GetString("LogRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request processed successfully.
        /// </summary>
        internal static string LogSuccess {
            get {
                return ResourceManager.GetString("LogSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request was not successful, bad parameters.
        /// </summary>
        internal static string ResponseBadParams {
            get {
                return ResourceManager.GetString("ResponseBadParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request was not successful, internal error.
        /// </summary>
        internal static string ResponseRequestFailed {
            get {
                return ResourceManager.GetString("ResponseRequestFailed", resourceCulture);
            }
        }
    }
}
